# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0
ci:
  autofix_commit_msg: "fix: auto fixes"
  autoupdate_commit_msg: "chore: autoupdate"
repos:
  - repo: https://github.com/lihop/godot-hooks
    rev: v1.0.0
    hooks:
      - id: check-git-archive
        args: [addons/godot_xterm]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.5.0
    hooks:
      - id: gdformat
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--ignore-words-list=thirdparty] # FIXME: Rename the thirdparty directory to third-party.
        exclude: ".*package-lock.json|.*demo.txt|.*fonts.*LICENSE|.*THIRDPARTY_NOTICES.*|.*.svg"
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        exclude: '.*\.(js|json)'
